# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.User')),
                ('otherusers', models.ManyToManyField(related_name='otherusers', to='users.User')),
            ],
            managers=[
                ('wishManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
